version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - sloglint
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 5
    gocyclo:
      min-complexity: 50
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    sloglint:
      attr-only: true
    staticcheck:
      checks:
        - all
        - -SA1019
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: d.GetOkExists is deprecated
    paths:
      - importer-script/*
      - docs
      - examples
      - provider-migration-script
      - templates
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
severity:
  default: error
  rules:
    - linters:
        - gofmt
      severity: info
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - https://github.com/kionsoftware/terraform-provider-kion
  exclusions:
    generated: lax
    paths:
      - importer-script/*
      - docs
      - examples
      - provider-migration-script
      - templates
      - third_party$
      - builtin$
      - examples$
