---
layout: ""
page_title: "Kion Terraform Provider"
description: |-
  The Kion Terraform Provider allows you to interact with an installation of Kion.
---

# Kion Terraform Provider

The Kion Terraform Provider allows you to interact with an installation of Kion.

## Example Usage

```terraform
provider "kion" {
  # If these are commented out, they will be loaded from
  # environment variables.
  # url = "https://kion.example.com"
  # apikey = "key here"
}
```

### Resource and Data Source Examples

For detailed examples of how to use specific resources and data sources, please refer to their respective documentation pages within this provider's documentation.

<!-- schema generated by tfplugindocs -->
## Schema

### Required

- `apikey` (String, Sensitive) The API key generated from Kion. Example: app_1_XXXXXXXXXXXX.
- `url` (String) The URL of a Kion installation. Example: <https://kion.example.com>.

### Optional

- `apipath` (String) The base path of the API. Defaults to /api
- `skipsslvalidation` (Boolean) If true, will skip SSL validation.

### Environment Variables

If you want to configure the provider via environment variables, you can use these below.

```bash
export TF_VAR_KION_APIKEY="app_1_XXXXXXXXXXXX"
export TF_VAR_KION_URL="https://kion.example.com"
export TF_VAR_KION_SKIPSSLVALIDATION="false"
```

### Importing Resource State

This provider does support [importing state for resources](https://developer.hashicorp.com/terraform/cli/import). You will need to create the Terraform files and then you can run commands like this to generate the `terraform.tfstate` so you don't have to delete all your resources and then recreate them to work with Terraform:

```bash
# Initialize the project.
terraform init

# Import the resource from your environment - this assumes you have a module called
# 'aws-cloudformation-template' and you are importing into a resource you defined as 'AuditLogging'.
# The '20' at the end is the ID of the resource in Kion.
terraform import module.aws-cloudformation-template.kion_aws_cloudformation_template.AuditLogging 20

# Verify the state is correct - there shouldn't be any changes listed if you defined
# the resources correctly.
terraform plan
```
